name: Master Build and Publish
# For master push: Builds and publishes the development version to bintray/maven
on:
  push:
    branches:
      - master
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      MAVEN_CENTRAL_USER_NEW: ${{ secrets.MAVEN_CENTRAL_USER_NEW }}
      MAVEN_CENTRAL_PASSWORD_NEW: ${{ secrets.MAVEN_CENTRAL_PASSWORD_NEW }}
      MAVEN_CENTRAL_PGP_KEY: ${{ secrets.MAVEN_CENTRAL_PGP_KEY }}

    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: build test and publish
        run: ./gradlew assemble && ./gradlew check --info && && ./gradlew jcstress && ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -x check --info --stacktrace
        env:
          CI: true
